package com.ketech.po;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_role_privilege
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class SysRolePrivilege implements Serializable {
    /**
     * Database Column Remarks:
     *   角色ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_privilege.role_id
     *
     * @mbg.generated
     */
    private Long roleId;

    /**
     * Database Column Remarks:
     *   权限ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_privilege.privilege_is
     *
     * @mbg.generated
     */
    private Long privilegeIs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_role_privilege
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_privilege.role_id
     *
     * @return the value of sys_role_privilege.role_id
     *
     * @mbg.generated
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_privilege.role_id
     *
     * @param roleId the value for sys_role_privilege.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_privilege.privilege_is
     *
     * @return the value of sys_role_privilege.privilege_is
     *
     * @mbg.generated
     */
    public Long getPrivilegeIs() {
        return privilegeIs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_privilege.privilege_is
     *
     * @param privilegeIs the value for sys_role_privilege.privilege_is
     *
     * @mbg.generated
     */
    public void setPrivilegeIs(Long privilegeIs) {
        this.privilegeIs = privilegeIs;
    }
}